// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SelecionarParaCasaPopular.Data.DataContext;

#nullable disable

namespace SelecionarParaCasaPopular.Data.Migrations
{
    [DbContext(typeof(FamiliasContext))]
    [Migration("20221202155632_migrationTesteModelagem")]
    partial class migrationTesteModelagem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("SelecionarParaCasaPopular.Data.Models.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pontos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Familia");
                });

            modelBuilder.Entity("SelecionarParaCasaPopular.Data.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dependente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RendaIndividual")
                        .HasColumnType("REAL");

                    b.Property<bool>("TitularDoCadastro")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("SelecionarParaCasaPopular.Data.Models.Pessoa", b =>
                {
                    b.HasOne("SelecionarParaCasaPopular.Data.Models.Familia", "Familia")
                        .WithMany("Membros")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("SelecionarParaCasaPopular.Data.Models.Familia", b =>
                {
                    b.Navigation("Membros");
                });
#pragma warning restore 612, 618
        }
    }
}
